[[pages]]
path = "./pages/text.py"
name = "æ–‡æœ¬é—®ç­”"
icon = "ğŸ“„"


[[pages]]
path = "./pages/voice.py"
name = "è¯­éŸ³åˆæˆ"
icon = "ğŸ¤"

[[pages]]
path = "./pages/human.py"
name = "æ•°å­—äºº"
icon = ":ğŸ’â€â™€ï¸:"


