[[pages]]
path = "./pages/text.py"
name = "æ–‡æœ¬ç¬‘è¯"
icon = "ğŸ“„"

[[pages]]
path = "./pages/picture.py"
name = "å›¾ç‰‡ç¬‘è¯"
icon = "ğŸŒ„"

[[pages]]
path = "./pages/voice.py"
name = "è¯­éŸ³åˆæˆ"
icon = "ğŸ¤"

[[pages]]
path = "./pages/human.py"
name = "æ•°å­—äºº"
icon = ":ğŸ’â€â™€ï¸:"


